-- Description: Populate FEATURES_PER_INTERVAL table with combined stock and sentiment features
INSERT INTO FIRSTDB.PUBLIC.FEATURES_PER_INTERVAL (
    SYMBOL,
    INTERVAL_TS,
    OPEN_PRICE,
    CLOSE_PRICE,
    HIGH_PRICE,
    LOW_PRICE,
    TOTAL_VOLUME,
    RETURN,
    VOLATILITY,
    AVG_SENTIMENT,
    NEWS_COUNT,
    SENTIMENT_RETURN_INTERACTION
)
SELECT
    s.SYMBOL,
    s.INTERVAL_TS,
    s.OPEN_PRICE,
    s.CLOSE_PRICE,
    s.HIGH_PRICE,
    s.LOW_PRICE,
    s.TOTAL_VOLUME,
    s.RETURN,
    s.VOLATILITY,
    sn.AVG_SENTIMENT,
    sn.NEWS_COUNT,
    s.RETURN * sn.AVG_SENTIMENT AS SENTIMENT_RETURN_INTERACTION
FROM FIRSTDB.PUBLIC.STOCK_FEATURES s
         LEFT JOIN FIRSTDB.PUBLIC.SENTIMENT_FEATURES sn
                   ON s.SYMBOL = sn.SYMBOL
                       AND s.INTERVAL_TS = sn.INTERVAL_TS
ORDER BY s.SYMBOL, s.INTERVAL_TS;

