--  Description: Populate SENTIMENT_FEATURES table with aggregated sentiment data

INSERT INTO FIRSTDB.PUBLIC.SENTIMENT_FEATURES (
    SYMBOL,
    INTERVAL_TS,
    AVG_SENTIMENT,
    NEWS_COUNT
)
SELECT
    s.TICKER AS SYMBOL,
    DATE_TRUNC('hour', a.PUBLISHED_AT) AS INTERVAL_TS,
    AVG(CAST(s.SENTIMENT_SCORE AS FLOAT)) AS AVG_SENTIMENT,
    COUNT(DISTINCT s.ARTICLE_ID) AS NEWS_COUNT
FROM FIRSTDB.PUBLIC.NEWS_TICKER_SENTIMENT s
         JOIN FIRSTDB.PUBLIC.NEWS_ARTICLES a
              ON s.ARTICLE_ID = a.ID
GROUP BY s.TICKER, DATE_TRUNC('hour', a.PUBLISHED_AT)
ORDER BY SYMBOL, INTERVAL_TS;
