-- DDL for NEWS_TICKER_SENTIMENT table

create or replace TABLE FIRSTDB.PUBLIC.NEWS_TICKER_SENTIMENT (
	ARTICLE_ID NUMBER(38,0),
	TICKER VARCHAR(16777216),
	RELEVANCE_SCORE FLOAT,
	SENTIMENT_SCORE FLOAT,
	SENTIMENT_LABEL VARCHAR(16777216),
	foreign key (ARTICLE_ID) references FIRSTDB.PUBLIC.NEWS_ARTICLES(ID)
);