-- Snowflake DDL for STOCK_PRICES table

create or replace TABLE FIRSTDB.PUBLIC.STOCK_PRICES (
	SYMBOL VARCHAR(16777216),
	TS TIMESTAMP_LTZ(9),
	OPEN FLOAT,
	HIGH FLOAT,
	LOW FLOAT,
	CLOSE FLOAT,
	VOLUME FLOAT,
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
