-- Snowflake DDL for FEATURES_PER_INTERVAL table

create or replace TABLE FIRSTDB.PUBLIC.FEATURES_PER_INTERVAL (
	SYMBOL VARCHAR(16777216),
	INTERVAL_TS TIMESTAMP_NTZ(9),
	OPEN_PRICE FLOAT,
	CLOSE_PRICE FLOAT,
	HIGH_PRICE FLOAT,
	LOW_PRICE FLOAT,
	TOTAL_VOLUME FLOAT,
	RETURN FLOAT,
	VOLATILITY FLOAT,
	AVG_SENTIMENT FLOAT,
	NEWS_COUNT NUMBER(38,0),
	SENTIMENT_RETURN_INTERACTION FLOAT,
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
