-- DDL for table FIRSTDB.PUBLIC.SENTIMENT_FEATURES

create or replace TABLE FIRSTDB.PUBLIC.SENTIMENT_FEATURES (
	SYMBOL VARCHAR(16777216),
	INTERVAL_TS TIMESTAMP_NTZ(9),
	AVG_SENTIMENT FLOAT,
	NEWS_COUNT NUMBER(38,0),
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);