-- DDL for table STOCK_FEATURES

create or replace TABLE FIRSTDB.PUBLIC.STOCK_FEATURES (
	SYMBOL VARCHAR(16777216),
	INTERVAL_TS TIMESTAMP_NTZ(9),
	OPEN_PRICE FLOAT,
	CLOSE_PRICE FLOAT,
	HIGH_PRICE FLOAT,
	LOW_PRICE FLOAT,
	TOTAL_VOLUME FLOAT,
	RETURN FLOAT,
	VOLATILITY FLOAT,
	LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);